### ISSUE TITLE
How to build SpiLoader

### ISSUE THREAD

**Issue by thatsitipl** [OpenNuvoton/N32905_NonOS_BSP#1]
I got TurboWriter to work but all the prebuilt SPILoader executables don't work for me. I don't have access to the KEIL uVision ide is there another way of compiling SPILoader for N32905U3DN?

**Comment by kchuang1** [comment]
Hi,

If you cannot use Keil to build the non-OS code, the alternate solution is Eclipse environment.
You can refer https://github.com/OpenNuvoton/N9H20_NonOS_BSP/blob/master/Documents/N9H20%20Eclipse%20User%20Manual.pdf to install the environment for N32905. The environment is same for ARM9 CPU.
Then, open the project under GCC folder with the Eclipse.

**Comment by thatsitipl** [comment]
Thanks
